### PR TITLE
Brazilian Portuguese voices words, misc, colors and alphabet

### PR DESCRIPTION
**Pull request by marcosd5000**
About 120 new words recorded for pt_BR/misc, pt_BR/words, pt_BR/colors and pt_BR/alphabet.

### CODE REVIEW

**Comment by petitlapin** [comment]
Hi,

thank you for the new voices (sorry for delay, I didn't received a notification), I'll integrate it before the end of the year.

Johnny

**Comment by marcosd5000** [comment]
Hi Johnny;

Ok, no problem. Thanks. :)

**Comment by marcosd5000** [comment]
Actually, "Ship" means "Navio". If you chance, then it will appear "Barco" and my voice will say "Navio". haha
This remembers me my pull request from last year, this same thing happens with "face" voice. I chanced from "Face" to "Rosto", but still showing "Face"...
Both "Barco" and "Face" not wrong, but I made this changes to use words more "popular"...

But, thanks again.

Marcos D.

**Comment by petitlapin** [comment]
No, sorry, I switched... In the code/activity, it will be written "navio" (and I just changed to also display "rosto" instead of "face") to b ein sync with the voice!
Thank you

**Comment by marcosd5000** [comment]
Oh, that OK. haha
Really thanks. :)

**Pull request merged**
